services:
  semaphore:
    ports:
      - '4000:3000'
    image: docker.io/semaphoreui/semaphore:v2.16.47
    container_name: semaphore-core
    volumes:
      - semaphore_playbook:/tmp/semaphore/
      - semaphore_ssh_keys:/home/semaphore/.ssh
    networks:
      - semaphore
    environment:
      SEMAPHORE_DB_USER: ${SEMAPHORE_DB_USER}
      SEMAPHORE_DB_PASS: ${SEMAPHORE_DB_PASS}
      SEMAPHORE_DB_HOST: semaphore-mariadb
      SEMAPHORE_DB_PORT: 3306
      SEMAPHORE_DB_DIALECT: mysql
      SEMAPHORE_DB: ${SEMAPHORE_DB}
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: ${SEMAPHORE_ADMIN_PASSWORD}
      SEMAPHORE_ADMIN_NAME: ${SEMAPHORE_ADMIN_NAME}
      SEMAPHORE_ADMIN_EMAIL: ${SEMAPHORE_ADMIN_EMAIL}
      SEMAPHORE_ADMIN: ${SEMAPHORE_ADMIN_NAME}
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: ${SEMAPHORE_ACCESS_KEY_ENCRYPTION}
      SEMAPHORE_LDAP_ACTIVATED: 'no'
      TZ: Europe/Warsaw
    depends_on:
      - semaphore-mariadb

  semaphore-mariadb:
    image: docker.io/library/mariadb:11.8-ubi
    container_name: semaphore-mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - semaphore-mariadb_data:/var/lib/mysql
    networks:
      - semaphore
    environment:
      MYSQL_DATABASE: ${SEMAPHORE_DB}
      MYSQL_USER: ${SEMAPHORE_DB_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${SEMAPHORE_DB_PASS}
    ports:
      - '3307:3306'

volumes:
  semaphore-mariadb_data:
  semaphore_playbook:
  semaphore_ssh_keys:

networks:
  semaphore:
    driver: bridge
