services:
  prometheus:
    image: docker.io/prom/prometheus:v3.7.3
    container_name: prometheus
    ports:
      - '9080:9090'
    volumes:
      - prometheus_data:/prometheus
      - /home/whoami/repo/homelab/podman/monitoring/configs/prometheus:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - monitoring

  alertmanager:
    image: docker.io/prom/alertmanager:v0.28.1
    container_name: alertmanager
    ports:
      - '9093:9093'
    volumes:
      - /home/whoami/repo/homelab/podman/monitoring/configs/alertmanager:/etc/alertmanager/
      - alertmanager-data:/data
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    networks:
      - monitoring

  grafana:
    image: docker.io/grafana/grafana:12.2.1
    container_name: grafana
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_AUTH_ANONYMOUS_ENABLED=false
    volumes:
      - grafana_data:/var/lib/grafana
      - /home/whoami/repo/homelab/podman/monitoring/configs/grafana_dashboards:/etc/grafana/provisioning/datasources
    networks:
      - monitoring

  pwrstat-exporter:
    image: docker.io/cardif99/pwrstat-exporter:latest
    container_name: pwrstat-exporter
    ports:
      - '8088:8088'
    networks:
      - monitoring
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/usb/hiddev0:/dev/usb/hiddev0
    privileged: true

  # nextcloud-exporter:
  #   image: docker.io/xperimental/nextcloud-exporter:0.9.0
  #   container_name: nextcloud-exporter
  #   restart: unless-stopped
  #   environment:
  #     - NEXTCLOUD_SERVER=${NEXTCLOUD_SERVER}
  #     - NEXTCLOUD_AUTH_TOKEN=${NEXTCLOUD_AUTH_TOKEN}
  #     - NEXTCLOUD_TLS_SKIP_VERIFY=${NEXTCLOUD_TLS_SKIP_VERIFY}
  #     - NEXTCLOUD_INFO_APPS=${NEXTCLOUD_INFO_APPS}
  #     - NEXTCLOUD_INFO_UPDATE=${NEXTCLOUD_INFO_UPDATE}
  #   ports:
  #     - "9205:9205"
  #   networks:
  #     - monitoring
  #     - nextcloud_net

  podman-exporter:
    image: quay.io/navidys/prometheus-podman-exporter
    container_name: podman-exporter
    restart: unless-stopped
    ports:
      - '9882:9882'
    environment:
      CONTAINER_HOST: tcp://127.0.0.1:2375
    network_mode: host 
    volumes: []

networks:
  monitoring:
    driver: bridge
  nextcloud_net:
    external: true
    name: nextcloud_net

volumes:
  prometheus_data:
  alertmanager-data:
  grafana_data:
