services:
  navidrome:
    image: docker.io/deluan/navidrome:0.59.0
    container_name: navidrome
    user: ${PUID}:${PGID}
    ports:
      - "4533:4533"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      ND_PORT: 4533
      ND_REVERSEPROXYWHITELIST: "0.0.0.0/0"
    volumes:
      - navidrome_data:/data
      - "/mnt/nexus_storage/Muzyka/:/music:ro"

volumes:
  navidrome_data:
