global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1

scrape_configs:
- job_name: pve
  static_configs:
    - targets:
        - '10.0.0.2'
  metrics_path: /pve
  params:
    module: [default]
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: 10.0.0.4:9221 

- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - 10.0.0.4:9090
    
- job_name: speedtest-exporter
  scrape_interval: 10m
  scrape_timeout: 2m
  static_configs:
  - targets:
    - 10.0.0.4:9798

- job_name: "cadvisor-exporter"
  static_configs:
  - targets:
    - 10.0.0.4:9998
