---
- name: Add ansible user
  hosts: all
  gather_facts: true
  tasks:
    - name: Display OS Family
      ansible.builtin.debug:
        msg: "The OS family for {{ inventory_hostname }} is {{ ansible_os_family }}"

    - name: Add ansible user
      ansible.builtin.user:
        name: ansible
        groups:
          - sudo
        append: true
        state: present
        shell: /bin/bash
        create_home: true

    - name: Copy SSH key to ansible user
      ansible.posix.authorized_key:
        user: ansible
        state: present
        key: "{{ lookup('file', '~/.ssh/dev_keys/homelab/ansible.pub') }}"

    - name: Make sudo without password for ansible user
      ansible.builtin.copy:
        dest: /etc/sudoers.d/80-ansible-sudo-user
        content: "whoami ALL=(ALL) NOPASSWD:ALL"
        mode: '0440'
