---
- hosts: docker
  become: true
  tasks:
    - name: Install required packages
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: true

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present
        update_cache: true

    - name: Install Docker
      ansible.builtin.apt:
        name: docker-ce
        state: present
        update_cache: true

    - name: Ensure Docker service is enabled and running
      ansible.builtin.systemd:
        name: docker
        enabled: true
        state: started
