---
- name: Setup machine
  hosts: all
  gather_facts: true
  become: true
  tasks:

    - name: Display OS Family
      ansible.builtin.debug:
        msg: "The OS family for {{ inventory_hostname }} is {{ ansible_os_family }}"

    - name: "Updating and Upgrading Apt Packages"
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
        upgrade: safe
      when: ansible_os_family == "Debian"

    - name: Install packages for Debian/Ubuntu
      ansible.builtin.apt:
        name:
          - build-essential
          - git
          - vim
          - curl
          - wget
          - htop
          - tar
          - net-tools
          - unzip
          - zsh
          - fzf
          - apt-transport-https
          - ca-certificates
          - gnupg
          - lsb-release
          - sudo
        state: present
      when: ansible_os_family == "Debian"
