---
- name: Update and upgrade
  hosts: all
  gather_facts: true
  become: true
  become_user: root

  tasks:
    - name: Updating and Upgrading Apt Packages
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
        upgrade: safe
      register: upgrade_result
      ignore_errors: true
