---
- name: Setup WireGuard VPN (WG-Easy) on Docker host
  hosts: vpn
  become: yes

  tasks:
    - name: Get VPN secrets from Vault
      community.hashi_vault.vault_kv2_get:
        url: "{{ ansible_hashi_vault_url }}"
        auth_method: approle
        role_id: "{{ vault_role_id }}"
        secret_id: "{{ vault_secret_id }}"
        engine_mount_point: "secrets"
        path: "vpn/wg-easy"
        validate_certs: false
      register: vpn_vault
      delegate_to: localhost
      vars:
        ansible_become: false
      become: no

    - name: Enable IP Forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        reload: yes

    - name: Ensure WireGuard config directory exists
      file:
        path: /opt/wireguard
        state: directory
        mode: '0700'

    - name: Deploy WG-Easy Container
      docker_container:
        name: wg-easy
        image: ghcr.io/wg-easy/wg-easy
        state: started
        restart_policy: unless-stopped
        capabilities:
          - NET_ADMIN
        volumes:
          - /opt/wireguard:/etc/wireguard
        ports:
          - "51820:51820/udp"
          - "51821:51821/tcp"
        env:
          WG_HOST: "{{ homelab_vpn_addres }}"
          PASSWORD_HASH: "{{ vpn_vault.secret.password | password_hash('bcrypt') }}"
          WG_DEFAULT_DNS: "1.1.1.1"
          WG_ALLOWED_IPS: "10.0.0.0/24"
          HTTP_PORT: "51821"
        sysctls:
          net.ipv4.conf.all.src_valid_mark: 1
          net.ipv4.ip_forward: 1