---
- hosts: Docker
  become: true
  tasks:
    - name: Add Docker GPG key for Debian/Ubuntu
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: ansible_os_family == "Debian"

    - name: Add Docker repository for Ubuntu
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        update_cache: true
      when: ansible_os_family == "Debian" and ansible_distribution == "Ubuntu"

    - name: Add Docker repository for Debian
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/debian{{ ansible_distribution_release }} stable"
        state: present
        update_cache: true
      when: ansible_os_family == "Debian" and ansible_distribution == "Debian"

    - name: Install Docker
      ansible.builtin.apt:
        name: docker-ce
        state: present
        update_cache: true
      when: ansible_os_family == "Debian"

    - name: Add authenticated user to Docker group
      ansible.builtin.user:
        name: "whoami"
        groups: docker
        append: true
      when: ansible_os_family == "Debian"
