services:
  transmission:
    image: docker.io/linuxserver/transmission:4.0.6
    container_name: transmission
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: Europe/Warsaw
    volumes:
      - /home/whoami/configs/transmission/config:/config
      - /mnt/nexus_storage/Downloaded/:/downloads
      - /home/whoami/configs/transmission/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413/tcp
      - 51413:51413/udp
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9091/transmission/web/ || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3
    logging:
      driver: journald
