services:
  npm:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: always
    dns:
      - 10.0.0.5
      - 1.1.1.1
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:81"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    volumes:
      - /home/whoami/configs/npm/data:/data
      - /home/whoami/configs/npm/letsencrypt:/etc/letsencrypt
    environment:
      - TZ=Europe/Warsaw
    logging:
      driver: journald
