---
name: pwrstat-exporter

services:
  pwrstat-exporter:
    image: cardif99/pwrstat-exporter:latest
    container_name: pwrstat-exporter
    restart: unless-stopped
    ports:
      - "8088:8088"
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/usb/hiddev0:/dev/usb/hiddev0
    privileged: true
