services:
  pihole:
    container_name: pihole
    image: docker.io/pihole/pihole:latest
    hostname: nexus
    environment:
      - TZ=Europe/Warsaw
      - FTLCONF_webserver_api_password=${PIHOLE_PASS}
      - FTLCONF_webserver_api_enabled=true
    volumes:
      - ${PIHOLE_DATA}:/etc/pihole
      - ${PIHOLE_DNSMASQ}:/etc/dnsmasq.d
    ports:
      - "{PIHOLE_TCP}"
      - "{PIHOLE_UDP}"
      - "8070:80/tcp"
    restart: always

  unbound:
    image: docker.io/mvance/unbound:latest
    container_name: unbound
    restart: always
    volumes:
      - ${UNBOUND_CONFIG}:/opt/unbound/etc/unbound/unbound.conf:ro
