all:
  children:
    Docker:
      hosts:
        docker:
          ansible_host: 10.0.0.4
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/homelab/root
          ansible_port: 22
    Linux_host:
      hosts:
        cockpit:
          ansible_host: 10.0.0.3
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/homelab/root
          ansible_port: 22
