services:
  nextcloud:
    image: docker.io/library/nextcloud:32.0.3
    container_name: nextcloud
    ports:
      - '8080:80'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/status.php"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    volumes:
      - /mnt/apps_data/nextcloud/:/var/www/html
      - /run/user/1000/podman/podman.sock:/run/user/1000/podman/podman.sock:ro
    environment:
      REDIS_HOST: nextcloud-redis
      NEXTCLOUD_APPAPI_DEPLOYMENT_DAEMON_DEFAULT: local
      MYSQL_HOST: nextcloud-mariadb
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      NEXTCLOUD_TRUSTED_DOMAINS: nextcloud.whoaminet.it 10.0.0.5
      TRUSTED_PROXIES: 10.0.0.5 10.89.0.0/16
      OVERWRITEPROTOCOL: https
    networks:
      - nextcloud_net
    depends_on:
      - nextcloud-mariadb
    logging:
      driver: journald

  nextcloud-redis:
    image: docker.io/library/redis:8.2.2-bookworm
    container_name: nextcloud-redis
    ports:
      - '6379:6379'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - nextcloud_net
    logging:
      driver: journald

  nextcloud-mariadb:
    image: docker.io/library/mariadb:11.8-ubi
    container_name: nextcloud-mariadb
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h localhost --password='${MYSQL_PASSWORD}' || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      - nextcloud-mariadb_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_HOST: "%"
    networks:
      - nextcloud_net
    command:
      - mysqld
      - --transaction-isolation=READ-COMMITTED
      - --binlog-format=ROW
      - --bind-address=0.0.0.0
    logging:
      driver: journald

volumes:
  nextcloud-mariadb_data:

networks:
  nextcloud_net:
    driver: bridge
