---
name: ansible-semaphore
services:

  ansible-semaphore-mysql:
    restart: unless-stopped
    container_name: ansible-semaphore-mysql
    image: mysql:9.2.0
    hostname: ansible-semaphore-mysql
    volumes:
      - ansible-semaphore-mysql:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'no'
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  ansible-semaphore:
    restart: unless-stopped
    container_name: ansible-semaphore
    ports:
      - 4000:3000
    image: semaphoreui/semaphore:v2.12.14
    environment:
      SEMAPHORE_DB_USER: ${MYSQL_USER}
      SEMAPHORE_DB_PASS: ${MYSQL_PASSWORD}
      SEMAPHORE_DB_HOST: 10.0.0.3
      SEMAPHORE_DB_PORT: 3307
      SEMAPHORE_DB_DIALECT: mysql
      SEMAPHORE_DB: ${MYSQL_DATABASE}
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: ${SEMAPHORE_ADMIN_PASSWORD}
      SEMAPHORE_ADMIN_NAME: ${SEMAPHORE_ADMIN_NAME}
      SEMAPHORE_ADMIN_EMAIL: ${SEMAPHORE_ADMIN_EMAIL}
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: 
      SEMAPHORE_LDAP_ACTIVATED: 'no'
      TZ: Europe/Warsaw
    depends_on:
      - ansible-semaphore-mysql

volumes:
  ansible-semaphore-mysql:
